language: python

sudo: false

python:
  - "2.7_with_system_site_packages"
  - "3.4_with_system_site_packages"

addons:
  apt:
    packages:
    - python-scipy
    - python-numpy


install:
  - pip install -r requirements.txt
  - pip install pytest flake8
  - pip install .

script:
  - py.test
  - flake8
