sudo: false

language: python

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=flake8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-scipy

install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - tox -e $TOX_ENV
