language: python

sudo: false

python:
  - 2.7
  - 3.4

addons:
  apt:
    packages:
    - python-scipy
    - python-numpy

virtualenv:
  system_site_packages: true

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - pip install pytest flake8
  - pip install .

script:
  - py.test
  - flake8
