language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5

cache: pip

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - pip install pytest flake8
  - pip install .

script:
  - py.test
  - flake8
