sudo: false

language: python

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=flake8

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  - pip install -U pip

install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - tox -e $TOX_ENV
