sudo: false

language: python

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=flake8

install:
  - pip install tox
  - apt-get install python-scipy
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - tox -e $TOX_ENV
