language: python

sudo: false

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

install:
  - pip install -r requirements.txt
  - pip install pytest flake8
  - pip install .

script:
  - py.test
  - flake8
